import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function House(props) {
  const { nodes, materials } = useGLTF("/domm/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Material13.geometry}
          material={materials.Material13}
        />
        <mesh
          geometry={nodes.Material10.geometry}
          material={materials.Material10}
        />
        <mesh
          geometry={nodes.Material64.geometry}
          material={materials.Material64}
        />
        <mesh
          geometry={nodes.Material4.geometry}
          material={materials.Material4}
        />
        <mesh
          geometry={nodes.Material5.geometry}
          material={materials.Material5}
        />
        <mesh
          geometry={nodes.Material3.geometry}
          material={materials.Material3}
        />
        <mesh
          geometry={nodes.Material21.geometry}
          material={materials.Material21}
        />
        <mesh
          geometry={nodes.Material22.geometry}
          material={materials.Material22}
        />
        <mesh
          geometry={nodes.Material19.geometry}
          material={materials.Material19}
        />
        <mesh
          geometry={nodes.Material2.geometry}
          material={materials.Material2}
        />
        <mesh
          geometry={nodes.Material11.geometry}
          material={materials.Material11}
        />
        <mesh
          geometry={nodes.Material9.geometry}
          material={materials.Material9}
        />
        <mesh
          geometry={nodes.Material12.geometry}
          material={materials.Material12}
        />
        <mesh
          geometry={nodes.Material29.geometry}
          material={materials.Material29}
        />
        <mesh
          geometry={nodes.Material8.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_1.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_2.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_3.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_4.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_5.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_6.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_7.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_8.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_9.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_10.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_11.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_12.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_13.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_14.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_15.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_16.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_17.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_18.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_19.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_20.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material8_21.geometry}
          material={materials.Material8}
        />
        <mesh
          geometry={nodes.Material33.geometry}
          material={materials.Material33}
        />
        <mesh
          geometry={nodes.Material6.geometry}
          material={materials.Material6}
        />
        <mesh
          geometry={nodes.Material32.geometry}
          material={materials.Material32}
        />
        <mesh
          geometry={nodes.Material23.geometry}
          material={materials.Material23}
        />
        <mesh
          geometry={nodes.Material24.geometry}
          material={materials.Material24}
        />
        <mesh
          geometry={nodes.Material25.geometry}
          material={materials.Material25}
        />
        <lineSegments
          geometry={nodes.Material65.geometry}
          material={materials.Material65}
        />
        <mesh
          geometry={nodes.Material26.geometry}
          material={materials.Material26}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/domm/scene.gltf");
